export const USER_REPOSITORY_TOKEN = 'USER_REPOSITORY_TOKEN';
export const HOTEL_REPOSITORY_TOKEN = 'HOTEL_REPOSITORY_TOKEN';
export const RESERVATION_REPOSITORY_TOKEN = 'RESERVATION_REPOSITORY_TOKEN';
